import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useState, useEffect } from "react";
import { SpinnerDotted } from "spinners-react";

export default function Home() {
    const [text, setText] = useState("");

    useEffect(() => {
        document.body.style.backgroundColor = "#f8f9fa";

        fetch("/api/bionic")
            .then(res => res.json())
            .then(data => setText([data.text]))
            .catch(these_hands => console.error(these_hands));
    }, []);

    return (
        <div className={styles.container}>
            <Head>
                <title>BionicAPI Test</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>Testing out some text comparisons!</h1>

                <div className={styles.grid}>
                    <div className={styles.border}>
                        <p>
                            Hello friends from Facebook! Here I am typing out a bunch of verbose text so I can test out their API and just to see what this looks like on some sample text. I think I'll
                            really enjoy integrating this into some of my other projects so that I can have better accessibility for this. Dang, I sure feel like a kid again, trying to fill up a word
                            count for some kind of essay or research paper I'm writing. I think I'll have some pizza for dinner. Bottom text
                        </p>
                    </div>

                    <div style={{ justifyContent: "center", textAlign: "center" }} className={styles.border}>
                        {!text && <p className={styles.description}>"Currently loading text from BionicAPI!"</p>}
                        {!text && <SpinnerDotted size={100} thickness={100} speed={100} color="rgba(172, 57, 118, 1)" />}
                        {text && <p dangerouslySetInnerHTML={{ __html: text }}></p>}
                    </div>
                </div>
            </main>
        </div>
    );
}
